services:
  yolo-inference:
    build: .
    volumes:
      - ./images:/app/images  # Mount local images folder to container
      - ./output:/app/output  # Mount output
    command: ["--image", "images/fish.jpg"]  # Default image to process
